server:
  port: 44300
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat

logging:
  level:
    org.apache.coyote.http11: DEBUG

visma:
  api:
    base-url: "https://api.visma.net/v1"
    client-id: "din-client-id"
    client-secret: "din-client-secret"
    scope: "din-scope"
    tokenEndpoint: https://identity.vismaonline.com/connect/token
    redirect-uri: https://localhost:44300/callback

encryption:
  key: mysecretkey1234567890abcdefghijk